# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               渔歌唱晚
tagline:             相忘于江湖
url:                 http://www.twlr.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Suleyman Na
  url:               https://twitter.com/suleymanna1
  email:             suleyman.na@hotmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole
